<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net452;net461;net48;net6.0;net7.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="sample.xml" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="sample.xml">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\XmlToPox\XmlToPox.csproj" />
	</ItemGroup>

</Project>
